spring.datasource.url=jdbc:MySQL://localhost:3306/demo_sqli
spring.datasource.username=root
spring.datasource.password=Cuong2005@

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
# 🔥 Quan trọng để hiện error
server.error.include-message=always